-- Add INTERNAL_TRANSFER_OUT to tx_type enum
ALTER TYPE domain.tx_type ADD VALUE IF NOT EXISTS 'INTERNAL_TRANSFER_OUT';

-- Add INTERNAL_TRANSFER_IN to tx_type enum
ALTER TYPE domain.tx_type ADD VALUE IF NOT EXISTS 'INTERNAL_TRANSFER_IN';

-- Add comments for documentation
COMMENT ON TYPE domain.tx_type IS 'Transaction type enum: TRANSFER_OUT, TRANSFER_IN, INTERNAL_TRANSFER_OUT, INTERNAL_TRANSFER_IN, TOP_UP, PAYMENT, REFUND, WITHDRAWAL';
